version: "3.4"
services:
 admin-vue:
   image: node:alpine
   container_name: admin-vue
   entrypoint: /bin/sh
   ports:
     - 9054:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./vue-app
       target: /srv/app
   tty: true
